// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleDB.Server;

namespace PeopleDB.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201205044555_PersonAllowNullFK")]
    partial class PersonAllowNullFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PeopleDB.Shared.Models.Address", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Address1")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Address2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StateOrProvince")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("PeopleDB.Shared.Models.Person", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<uint>("sin")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("PeopleDB.Shared.Models.Pet", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("PetName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<uint>("PetRegistrationNumber")
                        .HasColumnType("int unsigned");

                    b.Property<string>("PetSpecies")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PeopleDB.Shared.Models.Vehicle", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("VehicleColor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VehicleIdNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VehicleMake")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<short>("VehicleYear")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("PeopleDB.Shared.Models.Address", b =>
                {
                    b.HasOne("PeopleDB.Shared.Models.Person", "Person")
                        .WithOne("address")
                        .HasForeignKey("PeopleDB.Shared.Models.Address", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleDB.Shared.Models.Pet", b =>
                {
                    b.HasOne("PeopleDB.Shared.Models.Person", "Person")
                        .WithMany("pets")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleDB.Shared.Models.Vehicle", b =>
                {
                    b.HasOne("PeopleDB.Shared.Models.Person", "Person")
                        .WithMany("vehicles")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
